/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        emerald: {
          50: 'hsl(var(--emerald-50) / <alpha-value>)',
          100: 'hsl(var(--emerald-100) / <alpha-value>)',
          200: 'hsl(var(--emerald-200) / <alpha-value>)',
          300: 'hsl(var(--emerald-300) / <alpha-value>)',
          400: 'hsl(var(--emerald-400) / <alpha-value>)',
          500: 'hsl(var(--emerald-500) / <alpha-value>)',
          600: 'hsl(var(--emerald-600) / <alpha-value>)',
          700: 'hsl(var(--emerald-700) / <alpha-value>)',
          800: 'hsl(var(--emerald-800) / <alpha-value>)',
          900: 'hsl(var(--emerald-900) / <alpha-value>)',
          950: 'hsl(var(--emerald-950) / <alpha-value>)',
        },
        green: {
          50: 'hsl(var(--emerald-50) / <alpha-value>)',
          100: 'hsl(var(--emerald-100) / <alpha-value>)',
          200: 'hsl(var(--emerald-200) / <alpha-value>)',
          300: 'hsl(var(--emerald-300) / <alpha-value>)',
          400: 'hsl(var(--emerald-400) / <alpha-value>)',
          500: 'hsl(var(--emerald-500) / <alpha-value>)',
          600: 'hsl(var(--emerald-600) / <alpha-value>)',
          700: 'hsl(var(--emerald-700) / <alpha-value>)',
          800: 'hsl(var(--emerald-800) / <alpha-value>)',
          900: 'hsl(var(--emerald-900) / <alpha-value>)',
          950: 'hsl(var(--emerald-950) / <alpha-value>)',
        },
        blue: {
          50: 'hsl(var(--emerald-50) / <alpha-value>)',
          100: 'hsl(var(--emerald-100) / <alpha-value>)',
          200: 'hsl(var(--emerald-200) / <alpha-value>)',
          300: 'hsl(var(--emerald-300) / <alpha-value>)',
          400: 'hsl(var(--emerald-400) / <alpha-value>)',
          500: 'hsl(var(--emerald-500) / <alpha-value>)',
          600: 'hsl(var(--emerald-600) / <alpha-value>)',
          700: 'hsl(var(--emerald-700) / <alpha-value>)',
          800: 'hsl(var(--emerald-800) / <alpha-value>)',
          900: 'hsl(var(--emerald-900) / <alpha-value>)',
          950: 'hsl(var(--emerald-950) / <alpha-value>)',
        },
        teal: {
          50: 'hsl(var(--teal-50) / <alpha-value>)',
          100: 'hsl(var(--teal-100) / <alpha-value>)',
          200: 'hsl(var(--teal-200) / <alpha-value>)',
          300: 'hsl(var(--teal-300) / <alpha-value>)',
          400: 'hsl(var(--teal-400) / <alpha-value>)',
          500: 'hsl(var(--teal-500) / <alpha-value>)',
          600: 'hsl(var(--teal-600) / <alpha-value>)',
          700: 'hsl(var(--teal-700) / <alpha-value>)',
          800: 'hsl(var(--teal-800) / <alpha-value>)',
          900: 'hsl(var(--teal-900) / <alpha-value>)',
          950: 'hsl(var(--teal-950) / <alpha-value>)',
        },
        indigo: {
          50: 'hsl(var(--teal-50) / <alpha-value>)',
          100: 'hsl(var(--teal-100) / <alpha-value>)',
          200: 'hsl(var(--teal-200) / <alpha-value>)',
          300: 'hsl(var(--teal-300) / <alpha-value>)',
          400: 'hsl(var(--teal-400) / <alpha-value>)',
          500: 'hsl(var(--teal-500) / <alpha-value>)',
          600: 'hsl(var(--teal-600) / <alpha-value>)',
          700: 'hsl(var(--teal-700) / <alpha-value>)',
          800: 'hsl(var(--teal-800) / <alpha-value>)',
          900: 'hsl(var(--teal-900) / <alpha-value>)',
          950: 'hsl(var(--teal-950) / <alpha-value>)',
        },
        amber: {
          50: 'hsl(var(--amber-50) / <alpha-value>)',
          100: 'hsl(var(--amber-100) / <alpha-value>)',
          200: 'hsl(var(--amber-200) / <alpha-value>)',
          300: 'hsl(var(--amber-300) / <alpha-value>)',
          400: 'hsl(var(--amber-400) / <alpha-value>)',
          500: 'hsl(var(--amber-500) / <alpha-value>)',
          600: 'hsl(var(--amber-600) / <alpha-value>)',
          700: 'hsl(var(--amber-700) / <alpha-value>)',
          800: 'hsl(var(--amber-800) / <alpha-value>)',
          900: 'hsl(var(--amber-900) / <alpha-value>)',
          950: 'hsl(var(--amber-950) / <alpha-value>)',
        },
        slate: {
          50: 'hsl(var(--slate-50) / <alpha-value>)',
          100: 'hsl(var(--slate-100) / <alpha-value>)',
          200: 'hsl(var(--slate-200) / <alpha-value>)',
          300: 'hsl(var(--slate-300) / <alpha-value>)',
          400: 'hsl(var(--slate-400) / <alpha-value>)',
          500: 'hsl(var(--slate-500) / <alpha-value>)',
          600: 'hsl(var(--slate-600) / <alpha-value>)',
          700: 'hsl(var(--slate-700) / <alpha-value>)',
          800: 'hsl(var(--slate-800) / <alpha-value>)',
          900: 'hsl(var(--slate-900) / <alpha-value>)',
          950: 'hsl(var(--slate-950) / <alpha-value>)',
        },
      }
    },
  },
  plugins: [],
}
