# base image
FROM python:3.11-slim

# working dir
WORKDIR /app

# env (no .pyc, faster logs)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy code
COPY . .

# expose port
EXPOSE 8000

# run app (production server)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]