name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/DockerFile
        push: true
        provenance: false
        tags: ghcr.io/deepeshsharma11/commilk-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/deepeshsharma11/commilk-backend:latest
          docker stop commilk-backend || true
          docker rm commilk-backend || true
          docker run -d --name commilk-backend -p 8000:8000 \
            --env-file /home/${{ secrets.USER }}/.env \
            --restart unless-stopped \
            ghcr.io/deepeshsharma11/commilk-backend:latest